/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class AAditivaExpressaoSimples extends PExpressaoSimples
{
    private PExpressaoAditiva _expressaoAditiva_;

    public AAditivaExpressaoSimples()
    {
        // Constructor
    }

    public AAditivaExpressaoSimples(
        @SuppressWarnings("hiding") PExpressaoAditiva _expressaoAditiva_)
    {
        // Constructor
        setExpressaoAditiva(_expressaoAditiva_);

    }

    @Override
    public Object clone()
    {
        return new AAditivaExpressaoSimples(
            cloneNode(this._expressaoAditiva_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAditivaExpressaoSimples(this);
    }

    public PExpressaoAditiva getExpressaoAditiva()
    {
        return this._expressaoAditiva_;
    }

    public void setExpressaoAditiva(PExpressaoAditiva node)
    {
        if(this._expressaoAditiva_ != null)
        {
            this._expressaoAditiva_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoAditiva_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressaoAditiva_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressaoAditiva_ == child)
        {
            this._expressaoAditiva_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressaoAditiva_ == oldChild)
        {
            setExpressaoAditiva((PExpressaoAditiva) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
