/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class AAtribuicaoExpressao extends PExpressao
{
    private PVar _var_;
    private TAtribuicao _atribuicao_;
    private PExpressaoSimples _expressaoSimples_;

    public AAtribuicaoExpressao()
    {
        // Constructor
    }

    public AAtribuicaoExpressao(
        @SuppressWarnings("hiding") PVar _var_,
        @SuppressWarnings("hiding") TAtribuicao _atribuicao_,
        @SuppressWarnings("hiding") PExpressaoSimples _expressaoSimples_)
    {
        // Constructor
        setVar(_var_);

        setAtribuicao(_atribuicao_);

        setExpressaoSimples(_expressaoSimples_);

    }

    @Override
    public Object clone()
    {
        return new AAtribuicaoExpressao(
            cloneNode(this._var_),
            cloneNode(this._atribuicao_),
            cloneNode(this._expressaoSimples_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAtribuicaoExpressao(this);
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public TAtribuicao getAtribuicao()
    {
        return this._atribuicao_;
    }

    public void setAtribuicao(TAtribuicao node)
    {
        if(this._atribuicao_ != null)
        {
            this._atribuicao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atribuicao_ = node;
    }

    public PExpressaoSimples getExpressaoSimples()
    {
        return this._expressaoSimples_;
    }

    public void setExpressaoSimples(PExpressaoSimples node)
    {
        if(this._expressaoSimples_ != null)
        {
            this._expressaoSimples_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoSimples_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._atribuicao_)
            + toString(this._expressaoSimples_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._atribuicao_ == child)
        {
            this._atribuicao_ = null;
            return;
        }

        if(this._expressaoSimples_ == child)
        {
            this._expressaoSimples_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        if(this._atribuicao_ == oldChild)
        {
            setAtribuicao((TAtribuicao) newChild);
            return;
        }

        if(this._expressaoSimples_ == oldChild)
        {
            setExpressaoSimples((PExpressaoSimples) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
