/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class ACasaBlocoIf extends PBlocoIf
{
    private PCasaDecl _casaDecl_;

    public ACasaBlocoIf()
    {
        // Constructor
    }

    public ACasaBlocoIf(
        @SuppressWarnings("hiding") PCasaDecl _casaDecl_)
    {
        // Constructor
        setCasaDecl(_casaDecl_);

    }

    @Override
    public Object clone()
    {
        return new ACasaBlocoIf(
            cloneNode(this._casaDecl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACasaBlocoIf(this);
    }

    public PCasaDecl getCasaDecl()
    {
        return this._casaDecl_;
    }

    public void setCasaDecl(PCasaDecl node)
    {
        if(this._casaDecl_ != null)
        {
            this._casaDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._casaDecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._casaDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._casaDecl_ == child)
        {
            this._casaDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._casaDecl_ == oldChild)
        {
            setCasaDecl((PCasaDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
