/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class ACExpressaoComando extends PComando
{
    private PCEspressao _cEspressao_;

    public ACExpressaoComando()
    {
        // Constructor
    }

    public ACExpressaoComando(
        @SuppressWarnings("hiding") PCEspressao _cEspressao_)
    {
        // Constructor
        setCEspressao(_cEspressao_);

    }

    @Override
    public Object clone()
    {
        return new ACExpressaoComando(
            cloneNode(this._cEspressao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACExpressaoComando(this);
    }

    public PCEspressao getCEspressao()
    {
        return this._cEspressao_;
    }

    public void setCEspressao(PCEspressao node)
    {
        if(this._cEspressao_ != null)
        {
            this._cEspressao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cEspressao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cEspressao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cEspressao_ == child)
        {
            this._cEspressao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cEspressao_ == oldChild)
        {
            setCEspressao((PCEspressao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
