/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class AComandosComando extends PComando
{
    private PCompostoDec _compostoDec_;

    public AComandosComando()
    {
        // Constructor
    }

    public AComandosComando(
        @SuppressWarnings("hiding") PCompostoDec _compostoDec_)
    {
        // Constructor
        setCompostoDec(_compostoDec_);

    }

    @Override
    public Object clone()
    {
        return new AComandosComando(
            cloneNode(this._compostoDec_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandosComando(this);
    }

    public PCompostoDec getCompostoDec()
    {
        return this._compostoDec_;
    }

    public void setCompostoDec(PCompostoDec node)
    {
        if(this._compostoDec_ != null)
        {
            this._compostoDec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._compostoDec_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._compostoDec_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._compostoDec_ == child)
        {
            this._compostoDec_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._compostoDec_ == oldChild)
        {
            setCompostoDec((PCompostoDec) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
