/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class AComparativoExpressaoSimples extends PExpressaoSimples
{
    private PExpressaoAditiva _exp1_;
    private TComparador _comparador_;
    private PExpressaoAditiva _exp2_;

    public AComparativoExpressaoSimples()
    {
        // Constructor
    }

    public AComparativoExpressaoSimples(
        @SuppressWarnings("hiding") PExpressaoAditiva _exp1_,
        @SuppressWarnings("hiding") TComparador _comparador_,
        @SuppressWarnings("hiding") PExpressaoAditiva _exp2_)
    {
        // Constructor
        setExp1(_exp1_);

        setComparador(_comparador_);

        setExp2(_exp2_);

    }

    @Override
    public Object clone()
    {
        return new AComparativoExpressaoSimples(
            cloneNode(this._exp1_),
            cloneNode(this._comparador_),
            cloneNode(this._exp2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComparativoExpressaoSimples(this);
    }

    public PExpressaoAditiva getExp1()
    {
        return this._exp1_;
    }

    public void setExp1(PExpressaoAditiva node)
    {
        if(this._exp1_ != null)
        {
            this._exp1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp1_ = node;
    }

    public TComparador getComparador()
    {
        return this._comparador_;
    }

    public void setComparador(TComparador node)
    {
        if(this._comparador_ != null)
        {
            this._comparador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comparador_ = node;
    }

    public PExpressaoAditiva getExp2()
    {
        return this._exp2_;
    }

    public void setExp2(PExpressaoAditiva node)
    {
        if(this._exp2_ != null)
        {
            this._exp2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp1_)
            + toString(this._comparador_)
            + toString(this._exp2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp1_ == child)
        {
            this._exp1_ = null;
            return;
        }

        if(this._comparador_ == child)
        {
            this._comparador_ = null;
            return;
        }

        if(this._exp2_ == child)
        {
            this._exp2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp1_ == oldChild)
        {
            setExp1((PExpressaoAditiva) newChild);
            return;
        }

        if(this._comparador_ == oldChild)
        {
            setComparador((TComparador) newChild);
            return;
        }

        if(this._exp2_ == oldChild)
        {
            setExp2((PExpressaoAditiva) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
