/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class ACondCondicao extends PCondicao
{
    private PValor _valor_;
    private TComparador _comparador_;
    private PValor2 _valor2_;

    public ACondCondicao()
    {
        // Constructor
    }

    public ACondCondicao(
        @SuppressWarnings("hiding") PValor _valor_,
        @SuppressWarnings("hiding") TComparador _comparador_,
        @SuppressWarnings("hiding") PValor2 _valor2_)
    {
        // Constructor
        setValor(_valor_);

        setComparador(_comparador_);

        setValor2(_valor2_);

    }

    @Override
    public Object clone()
    {
        return new ACondCondicao(
            cloneNode(this._valor_),
            cloneNode(this._comparador_),
            cloneNode(this._valor2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACondCondicao(this);
    }

    public PValor getValor()
    {
        return this._valor_;
    }

    public void setValor(PValor node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    public TComparador getComparador()
    {
        return this._comparador_;
    }

    public void setComparador(TComparador node)
    {
        if(this._comparador_ != null)
        {
            this._comparador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comparador_ = node;
    }

    public PValor2 getValor2()
    {
        return this._valor2_;
    }

    public void setValor2(PValor2 node)
    {
        if(this._valor2_ != null)
        {
            this._valor2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._valor_)
            + toString(this._comparador_)
            + toString(this._valor2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        if(this._comparador_ == child)
        {
            this._comparador_ = null;
            return;
        }

        if(this._valor2_ == child)
        {
            this._valor2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._valor_ == oldChild)
        {
            setValor((PValor) newChild);
            return;
        }

        if(this._comparador_ == oldChild)
        {
            setComparador((TComparador) newChild);
            return;
        }

        if(this._valor2_ == oldChild)
        {
            setValor2((PValor2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
