/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class ACParamChamaFuncao extends PChamaFuncao
{
    private TId _id_;
    private TParenteseE _parenteseE_;
    private PValores _valores_;
    private TParenteseD _parenteseD_;

    public ACParamChamaFuncao()
    {
        // Constructor
    }

    public ACParamChamaFuncao(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TParenteseE _parenteseE_,
        @SuppressWarnings("hiding") PValores _valores_,
        @SuppressWarnings("hiding") TParenteseD _parenteseD_)
    {
        // Constructor
        setId(_id_);

        setParenteseE(_parenteseE_);

        setValores(_valores_);

        setParenteseD(_parenteseD_);

    }

    @Override
    public Object clone()
    {
        return new ACParamChamaFuncao(
            cloneNode(this._id_),
            cloneNode(this._parenteseE_),
            cloneNode(this._valores_),
            cloneNode(this._parenteseD_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACParamChamaFuncao(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TParenteseE getParenteseE()
    {
        return this._parenteseE_;
    }

    public void setParenteseE(TParenteseE node)
    {
        if(this._parenteseE_ != null)
        {
            this._parenteseE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenteseE_ = node;
    }

    public PValores getValores()
    {
        return this._valores_;
    }

    public void setValores(PValores node)
    {
        if(this._valores_ != null)
        {
            this._valores_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valores_ = node;
    }

    public TParenteseD getParenteseD()
    {
        return this._parenteseD_;
    }

    public void setParenteseD(TParenteseD node)
    {
        if(this._parenteseD_ != null)
        {
            this._parenteseD_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenteseD_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._parenteseE_)
            + toString(this._valores_)
            + toString(this._parenteseD_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._parenteseE_ == child)
        {
            this._parenteseE_ = null;
            return;
        }

        if(this._valores_ == child)
        {
            this._valores_ = null;
            return;
        }

        if(this._parenteseD_ == child)
        {
            this._parenteseD_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._parenteseE_ == oldChild)
        {
            setParenteseE((TParenteseE) newChild);
            return;
        }

        if(this._valores_ == oldChild)
        {
            setValores((PValores) newChild);
            return;
        }

        if(this._parenteseD_ == oldChild)
        {
            setParenteseD((TParenteseD) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
