/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaracoesLocaisComandos extends PComandos
{
    private TColcheteE _colcheteE_;
    private PDeclaracoesLocais _declaracoesLocais_;
    private PListaComandos _listaComandos_;
    private TColcheteD _colcheteD_;

    public ADeclaracoesLocaisComandos()
    {
        // Constructor
    }

    public ADeclaracoesLocaisComandos(
        @SuppressWarnings("hiding") TColcheteE _colcheteE_,
        @SuppressWarnings("hiding") PDeclaracoesLocais _declaracoesLocais_,
        @SuppressWarnings("hiding") PListaComandos _listaComandos_,
        @SuppressWarnings("hiding") TColcheteD _colcheteD_)
    {
        // Constructor
        setColcheteE(_colcheteE_);

        setDeclaracoesLocais(_declaracoesLocais_);

        setListaComandos(_listaComandos_);

        setColcheteD(_colcheteD_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaracoesLocaisComandos(
            cloneNode(this._colcheteE_),
            cloneNode(this._declaracoesLocais_),
            cloneNode(this._listaComandos_),
            cloneNode(this._colcheteD_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaracoesLocaisComandos(this);
    }

    public TColcheteE getColcheteE()
    {
        return this._colcheteE_;
    }

    public void setColcheteE(TColcheteE node)
    {
        if(this._colcheteE_ != null)
        {
            this._colcheteE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colcheteE_ = node;
    }

    public PDeclaracoesLocais getDeclaracoesLocais()
    {
        return this._declaracoesLocais_;
    }

    public void setDeclaracoesLocais(PDeclaracoesLocais node)
    {
        if(this._declaracoesLocais_ != null)
        {
            this._declaracoesLocais_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracoesLocais_ = node;
    }

    public PListaComandos getListaComandos()
    {
        return this._listaComandos_;
    }

    public void setListaComandos(PListaComandos node)
    {
        if(this._listaComandos_ != null)
        {
            this._listaComandos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaComandos_ = node;
    }

    public TColcheteD getColcheteD()
    {
        return this._colcheteD_;
    }

    public void setColcheteD(TColcheteD node)
    {
        if(this._colcheteD_ != null)
        {
            this._colcheteD_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colcheteD_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._colcheteE_)
            + toString(this._declaracoesLocais_)
            + toString(this._listaComandos_)
            + toString(this._colcheteD_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._colcheteE_ == child)
        {
            this._colcheteE_ = null;
            return;
        }

        if(this._declaracoesLocais_ == child)
        {
            this._declaracoesLocais_ = null;
            return;
        }

        if(this._listaComandos_ == child)
        {
            this._listaComandos_ = null;
            return;
        }

        if(this._colcheteD_ == child)
        {
            this._colcheteD_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._colcheteE_ == oldChild)
        {
            setColcheteE((TColcheteE) newChild);
            return;
        }

        if(this._declaracoesLocais_ == oldChild)
        {
            setDeclaracoesLocais((PDeclaracoesLocais) newChild);
            return;
        }

        if(this._listaComandos_ == oldChild)
        {
            setListaComandos((PListaComandos) newChild);
            return;
        }

        if(this._colcheteD_ == oldChild)
        {
            setColcheteD((TColcheteD) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
