/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaracoesPrograma extends PPrograma
{
    private PDeclaracoes _declaracoes_;

    public ADeclaracoesPrograma()
    {
        // Constructor
    }

    public ADeclaracoesPrograma(
        @SuppressWarnings("hiding") PDeclaracoes _declaracoes_)
    {
        // Constructor
        setDeclaracoes(_declaracoes_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaracoesPrograma(
            cloneNode(this._declaracoes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaracoesPrograma(this);
    }

    public PDeclaracoes getDeclaracoes()
    {
        return this._declaracoes_;
    }

    public void setDeclaracoes(PDeclaracoes node)
    {
        if(this._declaracoes_ != null)
        {
            this._declaracoes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracoes_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declaracoes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declaracoes_ == child)
        {
            this._declaracoes_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declaracoes_ == oldChild)
        {
            setDeclaracoes((PDeclaracoes) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
