/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaracoesLocaisCompostoDec extends PCompostoDec
{
    private TChaveE _chaveE_;
    private PDeclaracoesLocais _declaracoesLocais_;
    private PListaComandos _listaComandos_;
    private TChaveD _chaveD_;

    public ADeclaracoesLocaisCompostoDec()
    {
        // Constructor
    }

    public ADeclaracoesLocaisCompostoDec(
        @SuppressWarnings("hiding") TChaveE _chaveE_,
        @SuppressWarnings("hiding") PDeclaracoesLocais _declaracoesLocais_,
        @SuppressWarnings("hiding") PListaComandos _listaComandos_,
        @SuppressWarnings("hiding") TChaveD _chaveD_)
    {
        // Constructor
        setChaveE(_chaveE_);

        setDeclaracoesLocais(_declaracoesLocais_);

        setListaComandos(_listaComandos_);

        setChaveD(_chaveD_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaracoesLocaisCompostoDec(
            cloneNode(this._chaveE_),
            cloneNode(this._declaracoesLocais_),
            cloneNode(this._listaComandos_),
            cloneNode(this._chaveD_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaracoesLocaisCompostoDec(this);
    }

    public TChaveE getChaveE()
    {
        return this._chaveE_;
    }

    public void setChaveE(TChaveE node)
    {
        if(this._chaveE_ != null)
        {
            this._chaveE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._chaveE_ = node;
    }

    public PDeclaracoesLocais getDeclaracoesLocais()
    {
        return this._declaracoesLocais_;
    }

    public void setDeclaracoesLocais(PDeclaracoesLocais node)
    {
        if(this._declaracoesLocais_ != null)
        {
            this._declaracoesLocais_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracoesLocais_ = node;
    }

    public PListaComandos getListaComandos()
    {
        return this._listaComandos_;
    }

    public void setListaComandos(PListaComandos node)
    {
        if(this._listaComandos_ != null)
        {
            this._listaComandos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaComandos_ = node;
    }

    public TChaveD getChaveD()
    {
        return this._chaveD_;
    }

    public void setChaveD(TChaveD node)
    {
        if(this._chaveD_ != null)
        {
            this._chaveD_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._chaveD_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._chaveE_)
            + toString(this._declaracoesLocais_)
            + toString(this._listaComandos_)
            + toString(this._chaveD_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._chaveE_ == child)
        {
            this._chaveE_ = null;
            return;
        }

        if(this._declaracoesLocais_ == child)
        {
            this._declaracoesLocais_ = null;
            return;
        }

        if(this._listaComandos_ == child)
        {
            this._listaComandos_ = null;
            return;
        }

        if(this._chaveD_ == child)
        {
            this._chaveD_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._chaveE_ == oldChild)
        {
            setChaveE((TChaveE) newChild);
            return;
        }

        if(this._declaracoesLocais_ == oldChild)
        {
            setDeclaracoesLocais((PDeclaracoesLocais) newChild);
            return;
        }

        if(this._listaComandos_ == oldChild)
        {
            setListaComandos((PListaComandos) newChild);
            return;
        }

        if(this._chaveD_ == oldChild)
        {
            setChaveD((TChaveD) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
