/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class ADimensoesRMatriz extends PRMatriz
{
    private PRMatriz _rMatriz_;
    private TColcheteE _colcheteE_;
    private PNumeroOuFuncao _numeroOuFuncao_;
    private TColcheteD _colcheteD_;

    public ADimensoesRMatriz()
    {
        // Constructor
    }

    public ADimensoesRMatriz(
        @SuppressWarnings("hiding") PRMatriz _rMatriz_,
        @SuppressWarnings("hiding") TColcheteE _colcheteE_,
        @SuppressWarnings("hiding") PNumeroOuFuncao _numeroOuFuncao_,
        @SuppressWarnings("hiding") TColcheteD _colcheteD_)
    {
        // Constructor
        setRMatriz(_rMatriz_);

        setColcheteE(_colcheteE_);

        setNumeroOuFuncao(_numeroOuFuncao_);

        setColcheteD(_colcheteD_);

    }

    @Override
    public Object clone()
    {
        return new ADimensoesRMatriz(
            cloneNode(this._rMatriz_),
            cloneNode(this._colcheteE_),
            cloneNode(this._numeroOuFuncao_),
            cloneNode(this._colcheteD_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADimensoesRMatriz(this);
    }

    public PRMatriz getRMatriz()
    {
        return this._rMatriz_;
    }

    public void setRMatriz(PRMatriz node)
    {
        if(this._rMatriz_ != null)
        {
            this._rMatriz_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rMatriz_ = node;
    }

    public TColcheteE getColcheteE()
    {
        return this._colcheteE_;
    }

    public void setColcheteE(TColcheteE node)
    {
        if(this._colcheteE_ != null)
        {
            this._colcheteE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colcheteE_ = node;
    }

    public PNumeroOuFuncao getNumeroOuFuncao()
    {
        return this._numeroOuFuncao_;
    }

    public void setNumeroOuFuncao(PNumeroOuFuncao node)
    {
        if(this._numeroOuFuncao_ != null)
        {
            this._numeroOuFuncao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numeroOuFuncao_ = node;
    }

    public TColcheteD getColcheteD()
    {
        return this._colcheteD_;
    }

    public void setColcheteD(TColcheteD node)
    {
        if(this._colcheteD_ != null)
        {
            this._colcheteD_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colcheteD_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._rMatriz_)
            + toString(this._colcheteE_)
            + toString(this._numeroOuFuncao_)
            + toString(this._colcheteD_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._rMatriz_ == child)
        {
            this._rMatriz_ = null;
            return;
        }

        if(this._colcheteE_ == child)
        {
            this._colcheteE_ = null;
            return;
        }

        if(this._numeroOuFuncao_ == child)
        {
            this._numeroOuFuncao_ = null;
            return;
        }

        if(this._colcheteD_ == child)
        {
            this._colcheteD_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._rMatriz_ == oldChild)
        {
            setRMatriz((PRMatriz) newChild);
            return;
        }

        if(this._colcheteE_ == oldChild)
        {
            setColcheteE((TColcheteE) newChild);
            return;
        }

        if(this._numeroOuFuncao_ == oldChild)
        {
            setNumeroOuFuncao((PNumeroOuFuncao) newChild);
            return;
        }

        if(this._colcheteD_ == oldChild)
        {
            setColcheteD((TColcheteD) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
