/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class AExpressaoComando extends PComando
{
    private PEspressaoDec _espressaoDec_;

    public AExpressaoComando()
    {
        // Constructor
    }

    public AExpressaoComando(
        @SuppressWarnings("hiding") PEspressaoDec _espressaoDec_)
    {
        // Constructor
        setEspressaoDec(_espressaoDec_);

    }

    @Override
    public Object clone()
    {
        return new AExpressaoComando(
            cloneNode(this._espressaoDec_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpressaoComando(this);
    }

    public PEspressaoDec getEspressaoDec()
    {
        return this._espressaoDec_;
    }

    public void setEspressaoDec(PEspressaoDec node)
    {
        if(this._espressaoDec_ != null)
        {
            this._espressaoDec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._espressaoDec_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._espressaoDec_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._espressaoDec_ == child)
        {
            this._espressaoDec_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._espressaoDec_ == oldChild)
        {
            setEspressaoDec((PEspressaoDec) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
