/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class AFuncaoCParamSDeclaracao extends PSDeclaracao
{
    private TId _id_;
    private TParenteseE _parenteseE_;
    private PParametros _parametros_;
    private TParenteseD _parenteseD_;
    private TColcheteE _colcheteE_;
    private PComandos _comandos_;
    private TColcheteD _colcheteD_;

    public AFuncaoCParamSDeclaracao()
    {
        // Constructor
    }

    public AFuncaoCParamSDeclaracao(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TParenteseE _parenteseE_,
        @SuppressWarnings("hiding") PParametros _parametros_,
        @SuppressWarnings("hiding") TParenteseD _parenteseD_,
        @SuppressWarnings("hiding") TColcheteE _colcheteE_,
        @SuppressWarnings("hiding") PComandos _comandos_,
        @SuppressWarnings("hiding") TColcheteD _colcheteD_)
    {
        // Constructor
        setId(_id_);

        setParenteseE(_parenteseE_);

        setParametros(_parametros_);

        setParenteseD(_parenteseD_);

        setColcheteE(_colcheteE_);

        setComandos(_comandos_);

        setColcheteD(_colcheteD_);

    }

    @Override
    public Object clone()
    {
        return new AFuncaoCParamSDeclaracao(
            cloneNode(this._id_),
            cloneNode(this._parenteseE_),
            cloneNode(this._parametros_),
            cloneNode(this._parenteseD_),
            cloneNode(this._colcheteE_),
            cloneNode(this._comandos_),
            cloneNode(this._colcheteD_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncaoCParamSDeclaracao(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TParenteseE getParenteseE()
    {
        return this._parenteseE_;
    }

    public void setParenteseE(TParenteseE node)
    {
        if(this._parenteseE_ != null)
        {
            this._parenteseE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenteseE_ = node;
    }

    public PParametros getParametros()
    {
        return this._parametros_;
    }

    public void setParametros(PParametros node)
    {
        if(this._parametros_ != null)
        {
            this._parametros_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametros_ = node;
    }

    public TParenteseD getParenteseD()
    {
        return this._parenteseD_;
    }

    public void setParenteseD(TParenteseD node)
    {
        if(this._parenteseD_ != null)
        {
            this._parenteseD_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenteseD_ = node;
    }

    public TColcheteE getColcheteE()
    {
        return this._colcheteE_;
    }

    public void setColcheteE(TColcheteE node)
    {
        if(this._colcheteE_ != null)
        {
            this._colcheteE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colcheteE_ = node;
    }

    public PComandos getComandos()
    {
        return this._comandos_;
    }

    public void setComandos(PComandos node)
    {
        if(this._comandos_ != null)
        {
            this._comandos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandos_ = node;
    }

    public TColcheteD getColcheteD()
    {
        return this._colcheteD_;
    }

    public void setColcheteD(TColcheteD node)
    {
        if(this._colcheteD_ != null)
        {
            this._colcheteD_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colcheteD_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._parenteseE_)
            + toString(this._parametros_)
            + toString(this._parenteseD_)
            + toString(this._colcheteE_)
            + toString(this._comandos_)
            + toString(this._colcheteD_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._parenteseE_ == child)
        {
            this._parenteseE_ = null;
            return;
        }

        if(this._parametros_ == child)
        {
            this._parametros_ = null;
            return;
        }

        if(this._parenteseD_ == child)
        {
            this._parenteseD_ = null;
            return;
        }

        if(this._colcheteE_ == child)
        {
            this._colcheteE_ = null;
            return;
        }

        if(this._comandos_ == child)
        {
            this._comandos_ = null;
            return;
        }

        if(this._colcheteD_ == child)
        {
            this._colcheteD_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._parenteseE_ == oldChild)
        {
            setParenteseE((TParenteseE) newChild);
            return;
        }

        if(this._parametros_ == oldChild)
        {
            setParametros((PParametros) newChild);
            return;
        }

        if(this._parenteseD_ == oldChild)
        {
            setParenteseD((TParenteseD) newChild);
            return;
        }

        if(this._colcheteE_ == oldChild)
        {
            setColcheteE((TColcheteE) newChild);
            return;
        }

        if(this._comandos_ == oldChild)
        {
            setComandos((PComandos) newChild);
            return;
        }

        if(this._colcheteD_ == oldChild)
        {
            setColcheteD((TColcheteD) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
