/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class AListaDeclaracoesLocais extends PDeclaracoesLocais
{
    private PDeclaracoesLocais _declaracoesLocais_;
    private PVariavel _variavel_;

    public AListaDeclaracoesLocais()
    {
        // Constructor
    }

    public AListaDeclaracoesLocais(
        @SuppressWarnings("hiding") PDeclaracoesLocais _declaracoesLocais_,
        @SuppressWarnings("hiding") PVariavel _variavel_)
    {
        // Constructor
        setDeclaracoesLocais(_declaracoesLocais_);

        setVariavel(_variavel_);

    }

    @Override
    public Object clone()
    {
        return new AListaDeclaracoesLocais(
            cloneNode(this._declaracoesLocais_),
            cloneNode(this._variavel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaDeclaracoesLocais(this);
    }

    public PDeclaracoesLocais getDeclaracoesLocais()
    {
        return this._declaracoesLocais_;
    }

    public void setDeclaracoesLocais(PDeclaracoesLocais node)
    {
        if(this._declaracoesLocais_ != null)
        {
            this._declaracoesLocais_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracoesLocais_ = node;
    }

    public PVariavel getVariavel()
    {
        return this._variavel_;
    }

    public void setVariavel(PVariavel node)
    {
        if(this._variavel_ != null)
        {
            this._variavel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variavel_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declaracoesLocais_)
            + toString(this._variavel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declaracoesLocais_ == child)
        {
            this._declaracoesLocais_ = null;
            return;
        }

        if(this._variavel_ == child)
        {
            this._variavel_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declaracoesLocais_ == oldChild)
        {
            setDeclaracoesLocais((PDeclaracoesLocais) newChild);
            return;
        }

        if(this._variavel_ == oldChild)
        {
            setVariavel((PVariavel) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
