/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class AListaParametros extends PParametros
{
    private PListaParametros _listaParametros_;

    public AListaParametros()
    {
        // Constructor
    }

    public AListaParametros(
        @SuppressWarnings("hiding") PListaParametros _listaParametros_)
    {
        // Constructor
        setListaParametros(_listaParametros_);

    }

    @Override
    public Object clone()
    {
        return new AListaParametros(
            cloneNode(this._listaParametros_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaParametros(this);
    }

    public PListaParametros getListaParametros()
    {
        return this._listaParametros_;
    }

    public void setListaParametros(PListaParametros node)
    {
        if(this._listaParametros_ != null)
        {
            this._listaParametros_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaParametros_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listaParametros_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listaParametros_ == child)
        {
            this._listaParametros_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listaParametros_ == oldChild)
        {
            setListaParametros((PListaParametros) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
