/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class AListaListaComandos extends PListaComandos
{
    private PListaComandos _listaComandos_;
    private PComando _comando_;

    public AListaListaComandos()
    {
        // Constructor
    }

    public AListaListaComandos(
        @SuppressWarnings("hiding") PListaComandos _listaComandos_,
        @SuppressWarnings("hiding") PComando _comando_)
    {
        // Constructor
        setListaComandos(_listaComandos_);

        setComando(_comando_);

    }

    @Override
    public Object clone()
    {
        return new AListaListaComandos(
            cloneNode(this._listaComandos_),
            cloneNode(this._comando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaListaComandos(this);
    }

    public PListaComandos getListaComandos()
    {
        return this._listaComandos_;
    }

    public void setListaComandos(PListaComandos node)
    {
        if(this._listaComandos_ != null)
        {
            this._listaComandos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaComandos_ = node;
    }

    public PComando getComando()
    {
        return this._comando_;
    }

    public void setComando(PComando node)
    {
        if(this._comando_ != null)
        {
            this._comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listaComandos_)
            + toString(this._comando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listaComandos_ == child)
        {
            this._listaComandos_ = null;
            return;
        }

        if(this._comando_ == child)
        {
            this._comando_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listaComandos_ == oldChild)
        {
            setListaComandos((PListaComandos) newChild);
            return;
        }

        if(this._comando_ == oldChild)
        {
            setComando((PComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
