/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class AListaListaArgs extends PListaArgs
{
    private PListaArgs _listaArgs_;
    private PExpressaoSimples _expressaoSimples_;

    public AListaListaArgs()
    {
        // Constructor
    }

    public AListaListaArgs(
        @SuppressWarnings("hiding") PListaArgs _listaArgs_,
        @SuppressWarnings("hiding") PExpressaoSimples _expressaoSimples_)
    {
        // Constructor
        setListaArgs(_listaArgs_);

        setExpressaoSimples(_expressaoSimples_);

    }

    @Override
    public Object clone()
    {
        return new AListaListaArgs(
            cloneNode(this._listaArgs_),
            cloneNode(this._expressaoSimples_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaListaArgs(this);
    }

    public PListaArgs getListaArgs()
    {
        return this._listaArgs_;
    }

    public void setListaArgs(PListaArgs node)
    {
        if(this._listaArgs_ != null)
        {
            this._listaArgs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaArgs_ = node;
    }

    public PExpressaoSimples getExpressaoSimples()
    {
        return this._expressaoSimples_;
    }

    public void setExpressaoSimples(PExpressaoSimples node)
    {
        if(this._expressaoSimples_ != null)
        {
            this._expressaoSimples_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoSimples_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listaArgs_)
            + toString(this._expressaoSimples_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listaArgs_ == child)
        {
            this._listaArgs_ = null;
            return;
        }

        if(this._expressaoSimples_ == child)
        {
            this._expressaoSimples_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listaArgs_ == oldChild)
        {
            setListaArgs((PListaArgs) newChild);
            return;
        }

        if(this._expressaoSimples_ == oldChild)
        {
            setExpressaoSimples((PExpressaoSimples) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
