/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class AListaDeclaracoesLocais extends PDeclaracoesLocais
{
    private PDeclaracoesLocais _declaracoesLocais_;
    private PVariavelDec _variavelDec_;

    public AListaDeclaracoesLocais()
    {
        // Constructor
    }

    public AListaDeclaracoesLocais(
        @SuppressWarnings("hiding") PDeclaracoesLocais _declaracoesLocais_,
        @SuppressWarnings("hiding") PVariavelDec _variavelDec_)
    {
        // Constructor
        setDeclaracoesLocais(_declaracoesLocais_);

        setVariavelDec(_variavelDec_);

    }

    @Override
    public Object clone()
    {
        return new AListaDeclaracoesLocais(
            cloneNode(this._declaracoesLocais_),
            cloneNode(this._variavelDec_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaDeclaracoesLocais(this);
    }

    public PDeclaracoesLocais getDeclaracoesLocais()
    {
        return this._declaracoesLocais_;
    }

    public void setDeclaracoesLocais(PDeclaracoesLocais node)
    {
        if(this._declaracoesLocais_ != null)
        {
            this._declaracoesLocais_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracoesLocais_ = node;
    }

    public PVariavelDec getVariavelDec()
    {
        return this._variavelDec_;
    }

    public void setVariavelDec(PVariavelDec node)
    {
        if(this._variavelDec_ != null)
        {
            this._variavelDec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variavelDec_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declaracoesLocais_)
            + toString(this._variavelDec_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declaracoesLocais_ == child)
        {
            this._declaracoesLocais_ = null;
            return;
        }

        if(this._variavelDec_ == child)
        {
            this._variavelDec_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declaracoesLocais_ == oldChild)
        {
            setDeclaracoesLocais((PDeclaracoesLocais) newChild);
            return;
        }

        if(this._variavelDec_ == oldChild)
        {
            setVariavelDec((PVariavelDec) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
