/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class AMatrizParametro extends PParametro
{
    private PTipo _tipo_;
    private TId _id_;
    private TChaveE _chaveE_;
    private TChaveD _chaveD_;

    public AMatrizParametro()
    {
        // Constructor
    }

    public AMatrizParametro(
        @SuppressWarnings("hiding") PTipo _tipo_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TChaveE _chaveE_,
        @SuppressWarnings("hiding") TChaveD _chaveD_)
    {
        // Constructor
        setTipo(_tipo_);

        setId(_id_);

        setChaveE(_chaveE_);

        setChaveD(_chaveD_);

    }

    @Override
    public Object clone()
    {
        return new AMatrizParametro(
            cloneNode(this._tipo_),
            cloneNode(this._id_),
            cloneNode(this._chaveE_),
            cloneNode(this._chaveD_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMatrizParametro(this);
    }

    public PTipo getTipo()
    {
        return this._tipo_;
    }

    public void setTipo(PTipo node)
    {
        if(this._tipo_ != null)
        {
            this._tipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipo_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TChaveE getChaveE()
    {
        return this._chaveE_;
    }

    public void setChaveE(TChaveE node)
    {
        if(this._chaveE_ != null)
        {
            this._chaveE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._chaveE_ = node;
    }

    public TChaveD getChaveD()
    {
        return this._chaveD_;
    }

    public void setChaveD(TChaveD node)
    {
        if(this._chaveD_ != null)
        {
            this._chaveD_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._chaveD_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipo_)
            + toString(this._id_)
            + toString(this._chaveE_)
            + toString(this._chaveD_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipo_ == child)
        {
            this._tipo_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._chaveE_ == child)
        {
            this._chaveE_ = null;
            return;
        }

        if(this._chaveD_ == child)
        {
            this._chaveD_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipo_ == oldChild)
        {
            setTipo((PTipo) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._chaveE_ == oldChild)
        {
            setChaveE((TChaveE) newChild);
            return;
        }

        if(this._chaveD_ == oldChild)
        {
            setChaveD((TChaveD) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
