/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class ANaoCasaBlocoIf extends PBlocoIf
{
    private PNaoCasaDecl _naoCasaDecl_;

    public ANaoCasaBlocoIf()
    {
        // Constructor
    }

    public ANaoCasaBlocoIf(
        @SuppressWarnings("hiding") PNaoCasaDecl _naoCasaDecl_)
    {
        // Constructor
        setNaoCasaDecl(_naoCasaDecl_);

    }

    @Override
    public Object clone()
    {
        return new ANaoCasaBlocoIf(
            cloneNode(this._naoCasaDecl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANaoCasaBlocoIf(this);
    }

    public PNaoCasaDecl getNaoCasaDecl()
    {
        return this._naoCasaDecl_;
    }

    public void setNaoCasaDecl(PNaoCasaDecl node)
    {
        if(this._naoCasaDecl_ != null)
        {
            this._naoCasaDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._naoCasaDecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._naoCasaDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._naoCasaDecl_ == child)
        {
            this._naoCasaDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._naoCasaDecl_ == oldChild)
        {
            setNaoCasaDecl((PNaoCasaDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
