/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class ASimplesExpressao extends PExpressao
{
    private PExpressaoSimples _expressaoSimples_;

    public ASimplesExpressao()
    {
        // Constructor
    }

    public ASimplesExpressao(
        @SuppressWarnings("hiding") PExpressaoSimples _expressaoSimples_)
    {
        // Constructor
        setExpressaoSimples(_expressaoSimples_);

    }

    @Override
    public Object clone()
    {
        return new ASimplesExpressao(
            cloneNode(this._expressaoSimples_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimplesExpressao(this);
    }

    public PExpressaoSimples getExpressaoSimples()
    {
        return this._expressaoSimples_;
    }

    public void setExpressaoSimples(PExpressaoSimples node)
    {
        if(this._expressaoSimples_ != null)
        {
            this._expressaoSimples_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoSimples_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressaoSimples_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressaoSimples_ == child)
        {
            this._expressaoSimples_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressaoSimples_ == oldChild)
        {
            setExpressaoSimples((PExpressaoSimples) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
