/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.node;

import Cmenos.analysis.*;

@SuppressWarnings("nls")
public final class AVariavelDeclaracao extends PDeclaracao
{
    private PVariavelDec _variavelDec_;

    public AVariavelDeclaracao()
    {
        // Constructor
    }

    public AVariavelDeclaracao(
        @SuppressWarnings("hiding") PVariavelDec _variavelDec_)
    {
        // Constructor
        setVariavelDec(_variavelDec_);

    }

    @Override
    public Object clone()
    {
        return new AVariavelDeclaracao(
            cloneNode(this._variavelDec_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariavelDeclaracao(this);
    }

    public PVariavelDec getVariavelDec()
    {
        return this._variavelDec_;
    }

    public void setVariavelDec(PVariavelDec node)
    {
        if(this._variavelDec_ != null)
        {
            this._variavelDec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variavelDec_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variavelDec_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variavelDec_ == child)
        {
            this._variavelDec_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variavelDec_ == oldChild)
        {
            setVariavelDec((PVariavelDec) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
