/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cmenos.analysis;

import Cmenos.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTId(TId node);
    void caseTNum(TNum node);
    void caseTBranco(TBranco node);
    void caseTComentarioLinha(TComentarioLinha node);
    void caseTComentarioD(TComentarioD node);
    void caseTComentarioCorpo(TComentarioCorpo node);
    void caseTSoma(TSoma node);
    void caseTMult(TMult node);
    void caseTIf(TIf node);
    void caseTElse(TElse node);
    void caseTInt(TInt node);
    void caseTString(TString node);
    void caseTReturn(TReturn node);
    void caseTVoid(TVoid node);
    void caseTWhile(TWhile node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
